### ISSUE TITLE
Retry Interval slows down Firefox until not responsive

### ISSUE THREAD

**Issue by vertigoelectric** [blackwind/reload-plus#7]
This is the closest thing to "contact" for this addon that I could find.

If I set a tab to reload at an interval, after a while the browser begins to slow down.  Eventually it becomes non-responsive and sometimes I have to kill the process with task manager.

I'm not sure why this would happen, but if there's any way to fix it I would love to know.

Thank you.

**Comment by blackwind** [comment]
The bad news here is that there's very little code driving retry intervals and therefore very little that could be or go wrong. I suspect that, if you manually reloaded the page the same number of times R+ does, you'd get the same result, which could be caused by literally anything from other add-ons to Firefox itself.

What you describe sounds like a memory issue. Each time you load (or reload) a page, Firefox chews through more and more RAM -- particularly if you're a heavy user of add-ons. In my experience, 32-bit builds of Firefox seem to begin choking at ~1.5GB of memory usage, and the higher that number goes, the more unresponsive it gets.

If your PC supports it, try the 64-bit build. Again, based on what you've described, I'm guessing you'll be pleasantly surprised.

If the 64-bit build doesn't help (or you can't run it), try to reproduce the problem in a clean profile. If you can and are able to provide more information, I'll take a closer look.

**Comment by vertigoelectric** [comment]
Thanks for your response.

After I posted here, I had some strange problem with Firefox. In attempts to fix it, I did things like refresh Firefox, restore backups, and remove some extensions.  After that, I got your response.

I took your suggestion and installed FF x64.  I honestly don't know why I had been using a 32 bit version in the first place.  Anyway, I tested R+ and had it reload a tab every 5 seconds and let it run for hours.  I had the resource monitor up as well.  When I came back, it had certainly been sucking up RAM and FF was a bit more sluggish, but it was manageable (unlike before).  I'm not sure if it's because of the changes I made to firefox x32 or if it was the upgrade to x64 (probably a bit of both), but it's good now.

I can't help but wonder, though, why reloading the page repeatedly would continue to eat up more and more RAM.  How do we get FF to flush the old data out when reloading a page?

**Comment by blackwind** [comment]
Glad to hear you're up and running.

To flush old data, you can visit about:memory and press "Minimize memory usage" under "Free memory". There are (or used to be?) add-ons that automate(d?) this, but either way, you'll find the results to be... less than what you'd hope/expect. Sadly, there isn't (and probably never will be) a good solution to this short of running the 64-bit build and restarting it every 24 hours or so.
